# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       nethogs

# >> macros
# << macros
%define __requires_exclude ^libncurses|libpcap|libstdc++|libtinfo.*$

Summary:    a small 'net top' tool
Version:    0.8.6
Release:    5
Group:      Applications/Internet
License:    GPL
URL:        https://github.com/raboof/nethogs
Source0:    https://github.com/raboof/nethogs/archive/%{name}-%{version}.tar.gz
Source100:  nethogs.yaml
Requires:   libpcap
Requires:   ncurses-libs
Requires:   libstdc++
BuildRequires:  pkgconfig(ncurses)
BuildRequires:  libpcap-devel
BuildRequires:  gcc-c++
BuildRequires:  desktop-file-utils
Obsoletes:   nethogs <= 0.8.1
Obsoletes:   openrepos-nethogs <= %{version}

%description
NetHogs is a small 'net top' tool. Instead of breaking the traffic down per
protocol or per subnet, like most tools do, it groups bandwidth by process.
NetHogs does not rely on a special kernel module to be loaded. If there's
suddenly a lot of network traffic, you can fire up NetHogs and immediately see
which PID is causing this. This makes it easy to indentify programs that have
gone wild and are suddenly taking up your bandwidth.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
make %{?_smp_mflags} -s -l4.8 nethogs
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
%{__make} install PREFIX="%{buildroot}"/usr
%{__install} -p -D -m 644 files/%{name}.desktop $RPM_BUILD_ROOT/%{_datadir}/applications/%{name}.desktop
for s in 86 108 128 172 256 512; do
%{__install} -p -D -m 644 files/%{name}_${s}.png $RPM_BUILD_ROOT/%{_datadir}/icons/hicolor/${s}x${s}/apps/%{name}.png
done
%{__install} -p -D -m 644 files/%{name}.svgz $RPM_BUILD_ROOT/%{_datadir}/icons/hicolor/scalable/apps/%{name}.svgz
# do not install man:
rm -r $RPM_BUILD_ROOT/%{_datadir}/man

# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%defattr(-, root, root, 0755)
%license COPYING
%{_sbindir}/nethogs
%defattr(-, root, root, 0644)
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/icons/hicolor/scalable/apps/%{name}.svgz
%{_datadir}/applications/%{name}.desktop
# >> files
# << files
